version: "3.7"
services:

  service-database:
    image: mysql:5.7
    ports: ["3306:3306"]
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=wordpress_tests

  wordpress:
    image: beamaustralia/php:7.4.0
    volumes:
        - './:/var/www'
    depends_on:
      - service-database
